version: '3.1'
services:
  ddns:
    image: qmcgaw/ddns-updater
    container_name: ddns
    environment:
      PUBLICIP_HTTP_PROVIDERS: ifconfig,ipinfo
      PUBLICIPV4_HTTP_PROVIDERS: ipify
      PUBLICIP_DNS_PROVIDERS: cloudflare
    ports:
      - 8000:8000/tcp
    volumes:
      - ~/env/docker/conf/ddns:/updater/data/
    networks:
      - self
  converter:
    image: chaniqure/converter:1.2
    container_name: converter
    ports:
      - 5000:5000
    volumes:
      - ~/env/docker/conf/converter/config.ini:/app/config.ini
      - ~/env/docker/conf/converter/clash.yml:/app/pkg/conf/subconverter_config/clash.yml
      - ~/env/docker/conf/converter/surge.yml:/app/pkg/conf/subconverter_config/surge.yml
      - ~/env/docker/conf/converter/ytoo.yml:/app/pkg/conf/subconverter_config/ytoo.yml
      - ~/env/docker/conf/converter/rule.yml:/app/pkg/conf/rule.yml
      - ~/env/docker/conf/converter/all_base.tpl:/app/subconverter/base/all_base.tpl
    networks:
      - self
networks:
  self:
    driver: bridge