kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mongo
  namespace: user
  labels:
    app: mongo
  annotations:
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
      annotations:
        kubesphere.io/creator: admin
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: volume-0gl6c3
          configMap:
            name: env
            items:
              - key: mongod.conf
                path: mongod.conf
            defaultMode: 420
        - name: data-path
          hostPath:
            path: /mnt/mongo
            type: ''
      containers:
        - name: mongo
          image: 'mongo:4.4.12'
          command:
            - mongod
            - '-f'
            - /etc/mongo/mongod.conf
          ports:
            - name: tcp-27017
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_DATABASE
              value: test
            - name: MONGO_INITDB_ROOT_USERNAME
              value: test
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: test123456
          resources: {}
          volumeMounts:
            - name: volume-0gl6c3
              readOnly: true
              mountPath: /etc/mongo/mongod.conf
              subPath: mongod.conf
            - name: data-path
              mountPath: /data/db
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: mongo
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
---
kind: Service
apiVersion: v1
metadata:
  name: mongo
  namespace: user
  labels:
    app: mongo
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/description: Mongo
spec:
  ports:
    - name: http-27017
      protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 27017
  selector:
    app: mongo
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
