kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nacos
  namespace: user
  labels:
    app: nacos
  annotations:
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nacos
      annotations:
        kubesphere.io/creator: admin
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: volume-kj86xv
          configMap:
            name: env
            items:
              - key: nacos.properies
                path: application.properties
            defaultMode: 420
      containers:
        - name: nacos
          image: nacos/nacos-server
          ports:
            - name: tcp-8848
              containerPort: 8848
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: volume-kj86xv
              readOnly: true
              mountPath: /home/nacos/conf/application.properties
              subPath: application.properties
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: nacos
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
---
kind: Service
apiVersion: v1
metadata:
  name: nacos
  namespace: user
  labels:
    app: nacos
  annotations:
    kubesphere.io/creator: admin
spec:
  ports:
    - name: http-8848
      protocol: TCP
      port: 8848
      targetPort: 8848
      nodePort: 8848
  selector:
    app: nacos
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
