kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper
  namespace: user
  labels:
    app: zookeeper
  annotations:
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper
      annotations:
        kubesphere.io/creator: admin
    spec:
      containers:
        - name: zookeeper
          image: 'docker.io/bitnami/zookeeper:3.8'
          ports:
            - name: tcp-2181
              containerPort: 2181
              protocol: TCP
            - name: tcp-2888
              containerPort: 2888
              protocol: TCP
            - name: tcp-3888
              containerPort: 3888
              protocol: TCP
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: 'yes'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: zookeeper
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
---
kind: Service
apiVersion: v1
metadata:
  name: zookeeper
  namespace: user
  labels:
    app: zookeeper
  annotations:
    kubesphere.io/creator: admin
spec:
  ports:
    - name: http-2181
      protocol: TCP
      port: 2181
      targetPort: 2181
      nodePort: 2181
  selector:
    app: zookeeper
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
